export const CASES = [
  {
    id: 'c1',
    provider: 'aws',
    label: 'AWS',
    labelClass: 'text-pixel-aws border-pixel-aws',
    title: 'THE "WEEKEND VM TESTING" INCIDENT',
    desc: 'An engineer spun up a massive m5.xlarge instance for a "quick 10-minute test" on Friday, then went on a weekend camping trip. We caught the 2.4x spike on Saturday morning. Downsized it and saved the team from a massive headache.',
    metric: '$1,395',
    metricLabel: '/ MONTH CLAWED BACK',
  },
  {
    id: 'c2',
    provider: 'azure',
    label: 'AZURE',
    labelClass: 'text-pixel-azure border-pixel-azure',
    title: 'THE LOG-HOARDING ARCHIVE CLEANUP',
    desc: 'An ecommerce portal was hoarding raw debug log files dating all the way back to 2018 in premium hot storage. We spotted costs rising for 6 consecutive days, drafted a cool-tier archive policy, and stopped the bleeding.',
    metric: '$450',
    metricLabel: '/ MONTH SAVED',
  },
  {
    id: 'c3',
    provider: 'multi',
    label: 'MULTI-CLOUD',
    labelClass: 'text-pixel-cyan border-pixel-cyan',
    title: 'AWS MONOPOLY BREAKER',
    desc: 'AWS accounted for 87% of this SaaS company\'s budget, leaving them at the mercy of their sales rep. We flagged the concentration risk, guided a migration of dev environments to GCP and Azure, and unlocked real price bargaining power.',
    metric: '22%',
    metricLabel: 'BILL SLICED',
  },
  {
    id: 'c4',
    provider: 'aws',
    label: 'AWS',
    labelClass: 'text-pixel-aws border-pixel-aws',
    title: 'US-EAST-1 EXIT STRATEGY',
    desc: 'us-east-1 accounted for 89% of all data transfer budgets and kept going down. By diversifying traffic to us-west-2 and eu-west-1, data transfer costs fell immediately and our infrastructure actually stayed online.',
    metric: '18%',
    metricLabel: 'TOTAL SAVED',
  },
  {
    id: 'c5',
    provider: 'multi',
    label: 'MULTI-CLOUD',
    labelClass: 'text-pixel-cyan border-pixel-cyan',
    title: 'THE SLEEP-SAVING AI DIGEST',
    desc: 'Our automated Gemini weekly summary dug up 3 rogue DB clusters that developers completely forgot to delete after a hackathon. Board-ready cost stories sent directly to the CTO without manual hunting.',
    metric: '12h',
    metricLabel: 'SAVED PER WEEK',
  },
  {
    id: 'c6',
    provider: 'azure',
    label: 'AZURE',
    labelClass: 'text-pixel-azure border-pixel-azure',
    title: 'THE GHOST DATABASE PURGE',
    desc: 'Azure SQL reached 68% of the platform\'s cost. A quick check flagged 3 database clones that were created for a QA run and left running for two months. We shut them down and slashed the bill instantly.',
    metric: '$830',
    metricLabel: '/ MONTH SAVED',
  },
  {
    id: 'c7',
    provider: 'gcp',
    label: 'GCP',
    labelClass: 'text-pixel-gcp border-pixel-gcp',
    title: 'BRUTE-FORCE BIGQUERY FIX',
    desc: 'A cron job was performing brute-force full-table scans every 30 minutes on millions of rows. We replaced it with incremental partitioned queries, dropping scan costs by 70% without breaking any dashboards.',
    metric: '$620',
    metricLabel: '/ MONTH SAVED',
  },
]

export const FAQ_ITEMS = [
  {
    q: 'HOW DOES CLOUD ACCOUNT LINKING WORK WITHOUT STEALING MY KEYS?',
    a: 'We never store your master cloud passwords (that would be a security nightmare). For AWS, we use secure IAM Role assumption with external IDs. For GCP, service accounts keys. For Azure, OAuth. All credentials are fully AES-256 encrypted before they even touch our database. Our own developers can\'t read them, so we sleep soundly at night—and you should too.',
  },
  {
    q: 'WHY IS THE ANOMALY ENGINE SET TO 2.0x BY DEFAULT?',
    a: "We calibrated this over months of testing. Below 1.5x, your inbox gets flooded with false alarms because someone ran a CPU-intensive test suite. Above 3x, your budget is already blown by the time we alert you. 2.0x is the sweet spot. On paid tiers, you can configure custom alert limits per category.",
  },
  {
    q: 'DO I HAVE TO MANUALLY UPLOAD FILES ALL THE TIME?',
    a: 'Nope. You can drag-and-drop CSV sheets whenever you feel like it, hook your CI/CD up to our simple POST /billing endpoint, or connect your cloud provider so our background workers fetch and sync your billing data automatically while you\'re asleep.',
  },
  {
    q: 'HOW DOES THE GEMINI AI INJECT COST CONTEXT?',
    a: 'It\'s like having a senior FinOps engineer locked in a chat room who knows your exact billing database. When you ask a question like "Why did my GCP costs spike yesterday?", our backend queries your latest billing summary, active anomalies, and recommendation lists, packs them neatly into the context, and sends it to Gemini. Your raw private data never leaves our secure loop.',
  },
  {
    q: 'WHAT KIND OF RETRO INFRASTRUCTURE IS RUNNING THIS?',
    a: 'A modular backend stack powered by Node.js, Express, and MongoDB Atlas. We use optimized compound indexes so your cost aggregations calculate in milliseconds, keeping the UI snappy and saving us hosting costs (we practice what we preach!).',
  },
  {
    q: 'ARE your SAVINGS ESTIMATES EXAGGERATED MARKETING NUMBERS?',
    a: 'No. We use highly conservative industry benchmarks rather than maximum hypothetical savings. Compute rightsizing is estimated at 32% (spot instance consolidation), storage lifecycle policies at 55% (archiving raw logs), and region diversifications at 12-20%. We track actual vs projected savings so you can audit our accuracy.',
  },
]
