export const PHASES = [
  {
    id: 1,
    badge: 'PHASE 1',
    badgeColor: 'bg-pixel-cyan text-black',
    title: 'CORE API ENGINE',
    desc: 'The foundation. REST API with 16 endpoints, MongoDB storage, validation middleware and structured logging.',
    features: ['POST /billing ingestion', 'Normalization service', '5 analytics endpoints', 'Correlation IDs'],
  },
  {
    id: 2,
    badge: 'PHASE 2',
    badgeColor: 'bg-pixel-yellow text-black',
    title: 'AUTH LAYER',
    desc: 'JWT-based authentication, user registration, rate limiting, and per-org data isolation.',
    features: ['JWT auth tokens', 'User/Org collections', 'Role-based access', 'Rate limiting (Redis)'],
  },
  {
    id: 3,
    badge: 'PHASE 3',
    badgeColor: 'bg-pixel-coral text-white',
    title: 'CLOUD ACCOUNT LINKING',
    desc: 'Real SaaS begins. Secure IAM role assumption, Azure AD OAuth, GCP service accounts — encrypted credentials stored per user.',
    features: ['AWS IAM Role / Access Key', 'Azure AD OAuth flow', 'GCP Service Account', 'Credential encryption at rest'],
  },
  {
    id: 4,
    badge: 'PHASE 4',
    badgeColor: 'bg-pixel-violet text-white',
    title: 'BACKGROUND PROCESSING',
    desc: 'Never block the request cycle. BullMQ + Redis queue workers handle normalization, anomaly detection, and recommendations asynchronously.',
    features: ['BullMQ job queues', 'Redis worker service', 'Cron-based sync', 'Failure recovery'],
  },
  {
    id: 5,
    badge: 'PHASE 5',
    badgeColor: 'bg-pixel-gcp text-black',
    title: 'GEMINI AI LAYER',
    desc: 'AI enhances — not replaces — rules. Gemini generates executive summaries, natural language cost explanations, and 30-day forecasts.',
    features: ['"Ask your cloud data"', 'Executive summaries', 'Cost forecast narrative', 'NL query interface'],
  },
  {
    id: 6,
    badge: 'PHASE 6',
    badgeColor: 'bg-pixel-pink text-black',
    title: 'PIXEL DASHBOARD',
    desc: 'React/Next.js frontend with Tailwind. Dark mode default. 8 pages including live trends, incident management, and AI chat.',
    features: ['Dashboard overview', 'Trends & Incidents UI', 'Recommendations tracker', 'AI Insights chat'],
  },
]
