export const SERVICES = [
  {
    id: 'billing',
    color: 'bg-pixel-mint',
    title: 'BILLING INGESTION',
    desc: 'Accepts raw cost data from AWS, GCP, and Azure via unified REST API. Validates, stores, and queues normalization pipeline automatically.',
    tag: 'POST /billing',
    icon: 'billing',
  },
  {
    id: 'trends',
    color: 'bg-pixel-pink',
    title: 'TREND ANALYSIS',
    desc: '7-day rolling averages per provider, service type, and region. Calculates deviation ratios to identify cost patterns before they become crises.',
    tag: 'GET /analytics/trends',
    icon: 'trends',
  },
  {
    id: 'anomaly',
    color: 'bg-pixel-yellow',
    title: 'ANOMALY DETECTION',
    desc: 'Three parallel detection engines: cost spike (2x threshold), service dominance (60% rule), vendor concentration (80% rule). Zero missed incidents.',
    tag: 'POST /incidents/detect',
    icon: 'anomaly',
  },
  {
    id: 'cloud',
    color: 'bg-pixel-blue',
    title: 'CLOUD ACCOUNT LINKING',
    desc: 'Secure IAM role assumption for AWS, Azure AD OAuth, GCP service accounts. Credentials encrypted at rest. Background workers fetch billing automatically.',
    tag: 'POST /cloud/connect',
    icon: 'cloud',
  },
  {
    id: 'ai',
    color: 'bg-pixel-lav',
    title: 'GEMINI AI INSIGHTS',
    desc: 'Ask your cloud data in plain English. "Why did my costs spike this week?" — Gemini synthesizes analytics into executive-ready narratives and forecasts.',
    tag: 'POST /ai/insights',
    icon: 'ai',
  },
  {
    id: 'optimize',
    color: 'bg-pixel-sage',
    title: 'OPTIMIZATION ENGINE',
    desc: 'Compute rightsizing, storage lifecycle policies, region diversification — backed by actual cost data. Average 15–20 % monthly savings. Tracks applied vs projected.',
    tag: 'GET /recommendations',
    icon: 'optimize',
  },
]
